name: pwbm
base: core18 
version: "0.1"
summary: Personal WayBack Machine
description: |
  Simple archiver for taking snapshots of web pages for later perusal

grade: stable
confinement: strict

parts:
  pwbm:
    source: snap/local
    plugin: dump
    stage-snaps:
      - monolith/latest/stable
    stage-packages:
      - wkhtmltopdf

apps:
  pwbm:
    command: pwbm
    plugs:
      - home
      - network
      - removable-media
  server:
    command: server.py
    plugs:
      - network-bind